---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "https://adelehedrick.github.io/Fall-2016-CSCI-3055U"
title: "Adele Hedrick - CSCI-3055U"
canonifyurls: true
params:
  Subtitle: "TA blog for Fall 2016 CSCI-3055U Programming Languages"
  description: "TA blog for Fall 2016 CSCI-3055U Programming Languages"
  AuthorName: "Adele Hedrick"
  GitHubUser: "adelehedrick"

