baseurl = "https://adelehedrick.github.io/"
title = "Syntactic Sugar"
theme = "hugo-universal-theme"
relativeURLs = true
languageCode = "en-us"
disqusShortname = "adele-hedrick-csci-3055u"
googleAnalytics = ""
pygmentsStyle = "tango"

# Define the number of posts per page
paginate = 10

[params]
    viewMorePostLink     = "/blog/"
    author = "Adele M. Hedrick"

    # Formspree.io email
    email = "adele@hedrick.ca"

    about_us = "<p>Masters of Computer Science Candidate, Software Developer and Aspiring Data Scientist.</p>"
		profile_pic = "img/profile_pic.jpeg"
    copyright = "Copyright (c) 2016, Adele Hedrick; all rights reserved."
    date_format = "2006-01-02"
    logo = "img/logo.png"
 #   address = ""

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

[[params.menu]]
    name = "Home"
    url  = "/"
    weight = 1

[[params.menu]]
    name = "Clojure"
    url  = "/clojure/"
    weight = 2

[[params.menu]]
    name = "Blog"
    url  = "/blog/"
    weight = 3


[[params.menu]]
    name = "Contact"
    url  = "/contact/"
    weight = 5

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = false
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = true
    icon = "fa fa-linkedin"
    title = "Connect with me on LinkedIn"
    subtitle = "I keep a very update profile and enjoy networking"
    link_url = "https://www.linkedin.com/in/adelehedrick"
    link_text = "Visit My Profile"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "Recent Posts"
subtitle = ""
